;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/ExactCraft/Content/Localization/ExactCraft
DestinationPath=Mods/ExactCraft/Content/Localization/ExactCraft
ManifestName=ExactCraft.manifest
ArchiveName=ExactCraft.archive
PortableObjectName=ExactCraft.po
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de
CulturesToGenerate=fr
CulturesToGenerate=es
CulturesToGenerate=pt-BR
CulturesToGenerate=pl
CulturesToGenerate=ru
CulturesToGenerate=zh-Hans
CulturesToGenerate=zh-Hant
CulturesToGenerate=ja
CulturesToGenerate=ko
CulturesToGenerate=it
CulturesToGenerate=uk
CulturesToGenerate=bg
CulturesToGenerate=cs
CulturesToGenerate=nl
CulturesToGenerate=ar
CulturesToGenerate=eo
CulturesToGenerate=fi
CulturesToGenerate=hu
CulturesToGenerate=lv
CulturesToGenerate=no
CulturesToGenerate=ro
CulturesToGenerate=sr-Cyrl
CulturesToGenerate=th
CulturesToGenerate=tr
CulturesToGenerate=vi
CulturesToGenerate=fa

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true

[GatherTextStep1]
CommandletClass=GenerateTextLocalizationResource
ResourceName=ExactCraft.locres

